### ISSUE TITLE
pm5 - outdated ext-pmmpthread

### ISSUE THREAD

**Issue by ItzxDwi** [DaisukeDaisuke/AndroidPHP#7]
Tittle says all

**Comment by ItzxDwi** [comment]
@DaisukeDaisuke

**Comment by DaisukeDaisuke** [comment]
Thank you for your issue
I am currently building the latest version
Please wait for a while until the release
https://github.com/DaisukeDaisuke/AndroidPHP/actions/runs/5497762460

**Comment by ItzxDwi** [comment]
> Thank you for your issue I am currently building the latest version Please wait for a while until the release https://github.com/DaisukeDaisuke/AndroidPHP/actions/runs/5497762460

The release failed @DaisukeDaisuke

**Comment by DaisukeDaisuke** [comment]
I found the cause.
The php8.2 branch still accesses gmplib.org
Compile locally

**Comment by ItzxDwi** [comment]
> I found the cause. The php8.2 branch still accesses gmplib.org Compile locally

If the build succes, tell me

**Comment by DaisukeDaisuke** [comment]
now available from the actions artifact
https://github.com/DaisukeDaisuke/AndroidPHP/actions/runs/5497762460

**Comment by DaisukeDaisuke** [comment]
Sorry I made you wait
release is now available
https://github.com/DaisukeDaisuke/AndroidPHP/releases/tag/8.1.20
