### ISSUE TITLE
pm5 - outdated ext-pmmpthreads

### ISSUE THREAD

**Issue by kanav67** [DaisukeDaisuke/AndroidPHP#8]
Latest pmmp-5 requires pthreads version 6.0.7.
@DaisukeDaisuke

**Comment by DaisukeDaisuke** [comment]
I'm sorry, but due to an error, pmmp cannot be compiled now, so I can't update it
Please refer to https://github.com/pmmp/PHP-Binaries/issues/176

**Comment by DaisukeDaisuke** [comment]
Thank you for your patience. I have identified the problem and released an updated binary with a workaround.
In the future, I may discontinue support for androidPHP if there are future events that make it difficult to compile.
https://github.com/DaisukeDaisuke/AndroidPHP/releases/tag/8.1.22

**Comment by kanav67** [comment]
Thanks for the time and work you give to this project. Hope you keep supporting this project.
